controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    master_position_controller:
      type: position_controllers/JointGroupPositionController

    slave_position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - master_shoulder_pan_joint
      - master_shoulder_lift_joint
      - master_elbow_joint
      - master_wrist_1_joint
      - master_wrist_2_joint
      - master_wrist_3_joint
      - slave_shoulder_pan_joint
      - slave_shoulder_lift_joint
      - slave_elbow_joint
      - slave_wrist_1_joint
      - slave_wrist_2_joint
      - slave_wrist_3_joint

master_position_controller:
  ros__parameters:
    joints:
      - master_shoulder_pan_joint
      - master_shoulder_lift_joint
      - master_elbow_joint
      - master_wrist_1_joint
      - master_wrist_2_joint
      - master_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

slave_position_controller:
  ros__parameters:
    joints:
      - slave_shoulder_pan_joint
      - slave_shoulder_lift_joint
      - slave_elbow_joint
      - slave_wrist_1_joint
      - slave_wrist_2_joint
      - slave_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
