controller_manager:
  ros__parameters:
    update_rate: 100  # 100 Hz control loop

    master_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    master_position_controller:
      type: position_controllers/JointGroupPositionController

master_position_controller:
  ros__parameters:
    joints:
      - master_joint1
      - master_joint2
      - master_joint3
      - master_joint4
      - master_joint5
      - master_joint6
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
