controller_manager:
  ros__parameters:
    update_rate: 100  # 100 Hz control loop

    slave_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    slave_position_controller:
      type: position_controllers/JointGroupPositionController

slave_position_controller:
  ros__parameters:
    joints:
      - slave_joint1
      - slave_joint2
      - slave_joint3
      - slave_joint4
      - slave_joint5
      - slave_joint6
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
